export var YOURDASH_SESSION_TYPE;
(function (YOURDASH_SESSION_TYPE) {
    YOURDASH_SESSION_TYPE[YOURDASH_SESSION_TYPE["web"] = 0] = "web";
    YOURDASH_SESSION_TYPE[YOURDASH_SESSION_TYPE["desktop"] = 1] = "desktop";
    YOURDASH_SESSION_TYPE[YOURDASH_SESSION_TYPE["cli"] = 2] = "cli";
    YOURDASH_SESSION_TYPE[YOURDASH_SESSION_TYPE["external"] = 3] = "external";
})(YOURDASH_SESSION_TYPE || (YOURDASH_SESSION_TYPE = {}));
//# sourceMappingURL=session.js.map