/*
 * Copyright ©2024 Ewsgit<https://github.com/ewsgit> and YourDash<https://github.com/yourdash> contributors.
 * YourDash is licensed under the MIT License. (https://ewsgit.mit-license.org)
 */

/**
 * This file is auto-generated by meta/generateApplicationRoutes.js don't edit this file for any reason
 * instead you should run `yarn run generate-application-routes`
*/

import loadable from "@loadable/component";
import React from "react";
import { Route, Routes } from "react-router";

const AppRouter=()=><Routes></Routes>;export default AppRouter
