/**
 * This file is auto-generated by meta/generateApplicationRoutes.js don't edit this file for any reason
 * instead you should run `yarn run generate-application-routes`
*/

import loadable from "@loadable/component";
import React from "react";
import { Route, Routes } from "react-router";

const Application0=loadable(()=>import("@yourdash/applications/uk-ewsgit-dash/web/index.tsx"));const Application1=loadable(()=>import("@yourdash/applications/uk-ewsgit-files/web/index.tsx"));const Application2=loadable(()=>import("@yourdash/applications/uk-ewsgit-store/web/index.tsx"));const Application3=loadable(()=>import("@yourdash/applications/uk-ewsgit-weather/web/index.tsx"));const Application4=loadable(()=>import("@yourdash/applications/uk-ewsgit-photos/web/index.tsx"));const AppRouter=()=><Routes><Route path={"uk-ewsgit-dash-frontend/*"} element={<Application0/>}/><Route path={"uk-ewsgit-files-frontend/*"} element={<Application1/>}/><Route path={"uk-ewsgit-store-frontend/*"} element={<Application2/>}/><Route path={"uk-ewsgit-weather-frontend/*"} element={<Application3/>}/><Route path={"uk-ewsgit-photos-frontend/*"} element={<Application4/>}/></Routes>;export default AppRouter
