/*
 * Copyright (c) 2023 YourDash contributors.
 * YourDash is licensed under the MIT License.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file is auto-generated by meta/generateApplicationRoutes.js don't edit this file for any reason
 */

import loadable from "@loadable/component";
import React from "react";
import { Route, Routes } from "react-router";

const Application0 = loadable( () => import( "./apps/code_studio" ) );
const Application1 = loadable( () => import( "./apps/dash" ) );
const Application2 = loadable( () => import( "./apps/diffusion_lab" ) );
const Application3 = loadable( () => import( "./apps/endpoints" ) );
const Application4 = loadable( () => import( "./apps/files" ) );
const Application5 = loadable( () => import( "./apps/global_db" ) );
const Application6 = loadable( () => import( "./apps/photos" ) );
const Application7 = loadable( () => import( "./apps/settings" ) );
const Application8 = loadable( () => import( "./apps/store" ) );
const Application9 = loadable( () => import( "./apps/weather" ) );
const Application10 = loadable( () => import( "./apps/yourdev" ) );

const AppRouter = () => (
  <Routes>
    <Route path={"code_studio/*"} element={<Application0/>}/>
    <Route path={"dash/*"} element={<Application1/>}/>
    <Route path={"diffusion_lab/*"} element={<Application2/>}/>
    <Route path={"endpoints/*"} element={<Application3/>}/>
    <Route path={"files/*"} element={<Application4/>}/>
    <Route path={"global_db/*"} element={<Application5/>}/>
    <Route path={"photos/*"} element={<Application6/>}/>
    <Route path={"settings/*"} element={<Application7/>}/>
    <Route path={"store/*"} element={<Application8/>}/>
    <Route path={"weather/*"} element={<Application9/>}/>
    <Route path={"yourdev/*"} element={<Application10/>}/>
  </Routes>
);

export default AppRouter;
