let waysToSayHello = [
  'Goeie dag',
  'Asalaam alaikum',
  'Barev dzez',
  'Kaixo',
  'Nǐ hǎo',
  'Dobar dan',
  'Dobré ráno',
  'Dobrý den',
  'Dobrý',
  'Hej',
  'Hallo',
  "Do'rud",
  'Mabuhay',
  'Bonjour',
  'Bonsoir',
  'Guten Tag',
  'Geia sas',
  'Aloha',
  'Shalom',
  'Namaste',
  'Jó napot',
  'Selamat pagi',
  'Selamat siang',
  'Selamat sore',
  'Selamat malam',
  'Dia duit',
  'Salve',
  'Ohayō gozaimasu',
  'Konnichiwa',
  'Konbanwa',
  'Annyeong haseyo',
  'God morgen',
  'God dag',
  'God kveld',
  'Tēnā koe',
  'Dzień dobry',
  'Olá',
  'Bună ziua',
  'Zdravstvuyte',
  'Hola',
  'Habari',
  'God dag',
  'Sawatdee krup',
  'Sawatdee ka',
  'Merhaba',
  'Xin chào',
  'Helô',
  'Sanibonani',
];

export default function generateHelloVariant(): string {
  let randomIndex = Math.floor(Math.random() * waysToSayHello.length);
  return waysToSayHello[randomIndex] || 'Hello';
}
