/**
 * This file is auto-generated by backend/src/core.ts during vite server startup don't edit this file for any reason
 */

import loadable from "@loadable/component";
import React from "react";
import { Route, Routes } from "react-router";

const Application0 = loadable(() => import("../../../../applications/uk-ewsgit-dash/web/index.tsx"));
const AppRouter = () => (
  <Routes>
    <Route
      path={"uk-ewsgit-dash/*"}
      element={<Application0 />}
    />
  </Routes>
);
export default AppRouter;
