var WEATHER_STATES;
(function (WEATHER_STATES) {
    WEATHER_STATES[WEATHER_STATES["CLEAR"] = 0] = "CLEAR";
    WEATHER_STATES[WEATHER_STATES["PARTLY_CLOUDY"] = 1] = "PARTLY_CLOUDY";
    WEATHER_STATES[WEATHER_STATES["CLOUDY"] = 2] = "CLOUDY";
    WEATHER_STATES[WEATHER_STATES["FOG"] = 3] = "FOG";
    WEATHER_STATES[WEATHER_STATES["LIGHT_RAIN"] = 4] = "LIGHT_RAIN";
    WEATHER_STATES[WEATHER_STATES["RAIN"] = 5] = "RAIN";
    WEATHER_STATES[WEATHER_STATES["HEAVY_RAIN"] = 6] = "HEAVY_RAIN";
    WEATHER_STATES[WEATHER_STATES["LIGHT_SNOW"] = 7] = "LIGHT_SNOW";
    WEATHER_STATES[WEATHER_STATES["SNOW"] = 8] = "SNOW";
    WEATHER_STATES[WEATHER_STATES["HEAVY_SNOW"] = 9] = "HEAVY_SNOW";
    WEATHER_STATES[WEATHER_STATES["LIGHT_RAIN_SHOWERS"] = 10] = "LIGHT_RAIN_SHOWERS";
    WEATHER_STATES[WEATHER_STATES["RAIN_SHOWERS"] = 11] = "RAIN_SHOWERS";
    WEATHER_STATES[WEATHER_STATES["HEAVY_RAIN_SHOWERS"] = 12] = "HEAVY_RAIN_SHOWERS";
    WEATHER_STATES[WEATHER_STATES["THUNDER"] = 13] = "THUNDER";
})(WEATHER_STATES || (WEATHER_STATES = {}));
export { WEATHER_STATES };
//# sourceMappingURL=weatherStates.js.map