/**
 * This file is auto-generated by meta/generateApplicationRoutes.js don't edit this file for any reason
 * instead you should run `yarn run generate-application-routes`
*/

import loadable from "@loadable/component";
import React from "react";
import { Route, Routes } from "react-router";

const Application0 = loadable( () => import( "applications/dash/frontend/index" ) );

const AppRouter = () => {
  return (
    <Routes>
      <Route path={"dash/*"} element={<Application0/>}/>
    </Routes>
  );
};

export default AppRouter
