/*
 * Copyright ©2023 @Ewsgit and YourDash contributors.
 * YourDash is licensed under the MIT License. (https://ewsgit.mit-license.org)
 */

import { existsSync, promises as fs } from "fs";
import path from "path";

/*
*
* ! NOTICE !
*
* THIS FILE HAS BEEN MODIFIED TO ALLOW FOR APPLICATIONS WITHOUT FRONTENDS
* HOWEVER, THIS HAS NOT BEEN TESTED.
*
* */

let fileTemplate =
  `/**
 * This file is auto-generated by meta/generateApplicationRoutes.js don't edit this file for any reason
 * instead you should run \`yarn run generate-application-routes\`
*/

import loadable from "@loadable/component";
import React from "react";
import { Route, Routes } from "react-router";

/* region loadable */
const AppRouter = () => {
  return (
    <Routes>
      {/* region routes */}
    </Routes>
  );
};

export default AppRouter
`;

let applicationsPathNames = await fs.readdir( path.resolve( process.cwd(), "../applications/" ) );

applicationsPathNames = applicationsPathNames.filter( name => name.indexOf( "." ) === -1 );

let loadableRegionReplacement = "";
let routeRegionReplacement = "";

let applicationHasLoaded = false;
applicationsPathNames.forEach( ( appName, ind ) => {
  if ( existsSync( path.resolve( process.cwd(), `../applications/${appName}/frontend/index.tsx` ) ) ) {
    loadableRegionReplacement += `const Application${ind} = loadable( () => import( "applications/${appName}/frontend/index" ) );\n`;
    if ( applicationHasLoaded ) {
      routeRegionReplacement += `<Route path={"${applicationsPathNames[ind]}/*"} element={<Application${ind}/>}/>`;
    } else {
      routeRegionReplacement += `\n      <Route path={"${applicationsPathNames[ind]}/*"} element={<Application${ind}/>}/>`;
    }
    applicationHasLoaded = true;
  }
} );

fileTemplate = fileTemplate.replace( "/* region loadable */", loadableRegionReplacement );
fileTemplate = fileTemplate.replace( "{/* region routes */}", routeRegionReplacement );

fs.writeFile( path.resolve( process.cwd(), "./src/app/AppRouter.tsx" ), fileTemplate ).then( () => {
  console.log( "Generated AppRouter.tsx Successfully" );
} );
