import { promises as fs } from "fs";
import path from "path";

let fileTemplate =
  `/**
 * This file is auto-generated by meta/generateApplicationRoutes.js don't edit this file for any reason
 * instead you should run \`yarn run generate-application-routes\`
*/

import loadable from "@loadable/component";
import React from "react";
import { Route, Routes } from "react-router";

/* region loadable */
const AppRouter = () => {
  return (
    <Routes>
      {/* region routes */}
    </Routes>
  );
};

export default AppRouter
`;

let applicationsPathNames = await fs.readdir( path.resolve( process.cwd(), "../applications/" ) );

applicationsPathNames = applicationsPathNames.filter( name => name.indexOf( "." ) === -1 )

let loadableRegionReplacement = "";
let routeRegionReplacement = "";
applicationsPathNames.forEach( ( app, ind ) => {
  loadableRegionReplacement += `const Application${ind} = loadable( () => import( "applications/${app}/frontend/index" ) );\n`;
  if ( ind === 0 ) {
    routeRegionReplacement += `<Route path={"${applicationsPathNames[ind]}/*"} element={<Application${ind}/>}/>`;
  } else {
    routeRegionReplacement += `\n      <Route path={"${applicationsPathNames[ind]}/*"} element={<Application${ind}/>}/>`;
  }
} );

fileTemplate = fileTemplate.replace( "/* region loadable */", loadableRegionReplacement );
fileTemplate = fileTemplate.replace( "{/* region routes */}", routeRegionReplacement );

fs.writeFile( path.resolve( process.cwd(), "./src/app/AppRouter.tsx" ), fileTemplate ).then( () => {
  console.log( "Generated AppRouter.tsx Successfully" );
} );
