var YOURDASH_INSTANCE_DISCOVERY_STATUS;
(function (YOURDASH_INSTANCE_DISCOVERY_STATUS) {
    YOURDASH_INSTANCE_DISCOVERY_STATUS[YOURDASH_INSTANCE_DISCOVERY_STATUS["MAINTENANCE"] = 0] = "MAINTENANCE";
    YOURDASH_INSTANCE_DISCOVERY_STATUS[YOURDASH_INSTANCE_DISCOVERY_STATUS["NORMAL"] = 1] = "NORMAL";
    YOURDASH_INSTANCE_DISCOVERY_STATUS[YOURDASH_INSTANCE_DISCOVERY_STATUS["INVISIBLE"] = 2] = "INVISIBLE";
})(YOURDASH_INSTANCE_DISCOVERY_STATUS || (YOURDASH_INSTANCE_DISCOVERY_STATUS = {}));
export { YOURDASH_INSTANCE_DISCOVERY_STATUS };
//# sourceMappingURL=discovery.js.map